micronaut:
  application:
    name: keyManagerGrpc

datasources:
  default:
    url: jdbc:mysql://localhost:3306/pix?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin
    driverClassName: "com.mysql.cj.jdbc.Driver"
    dialect: MYSQL

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl.auto: update
        show_sql: true
        format_sql: true